---
- name: Build Docker image for Java app
  hosts: localhost
  become: true
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: .
        name: jpetstoreapp_image
        tag: latest

- name: Run Docker container for Java app
  hosts: localhost
  become: true
  tasks:
    - name: Run Docker container
      community.docker.docker_container:
        name: jpetstoreapp_container
        image: jpetstoreapp_image:latest
        state: started
        ports:
          - "8080:8080"
